### ISSUE TITLE
Not working after recent firestick (2nd gen and 4K) OS update

### ISSUE THREAD

**Issue by tonyvr4** [codefaktor/FTVLaunchX#10] opened 2020-08-28 20:25 UTC
Recently an OS update for the Firestick 2md gen and Firestick 4K seems to have broken FTVLainchX and the home button feature.

1) When the OS update is installed the user is greeted with a notice of a new accessibility feature
2) Upon closing this notice the Firestick loads the default launcher and home screen
3) Running FTVLainchX or applying the ADB shell commands does not cause the device to automatically load the launcher and
the home button fuction to load the launcher does not work

I have verified this on the following devices and OS
Firestick 2nd Gen (OS 5.2.7.4)
Firestick 4K (OS 6.2.7.3)

Hopefully a quick resolution can be found
Thanks

**Comment by ikrowni** [comment] 2020-08-29 09:07
I'm having the same issue with all of my fire TV cubes and fire sticks as well. Hope this can be fixed. I hardly remember how horrible the original launcher looked and now I wanna throw the devices in the trash.

**Comment by tonyvr4** [comment] 2020-08-29 14:38
Agreed.  The developer of FTVLaunchX does not seem to check this or the github page.  Disappointing

**Comment by ErikAbele** [comment] 2020-08-29 15:16
Duplicate of #4 – closed.

**Closed as completed** 2020-08-29 15:16 UTC
Labels: duplicate
