### ISSUE TITLE
Still not working?

### ISSUE THREAD

**Issue by Leomm04** [codefaktor/FTVLaunchX#9] opened 2020-08-22 20:13 UTC
After updating my Fire TV Stick 2 LaunchX stopped working.
Will there be a fix?

**Comment by yurividal** [comment] 2020-08-22 21:42
6.2.7.3 broke this app again. we have to hope the dev is able to workarround it again.

**Comment by dadoremix** [comment] 2020-08-23 10:17
yep, broken also on my fire 4k afer update :(
but, after reboot 1st time working and then after not

**Comment by MPenSol** [comment] 2020-08-24 20:22
yep, i have the OS Version 6.2.7.3 too and it's not working. Hope for a workaround

**Comment by oathzed** [comment] 2020-08-24 22:08
@codefaktor

**Comment by oathzed** [comment] 2020-08-24 22:08
@ErikAbele

**Comment by RubixSolver99** [comment] 2020-08-27 20:08
Yeah I'm running FireOS 5.2.7.4 on my Firestick 2nd Gen, and isn't working for me. Sadly, Amazon seemed to release another patch.

**Comment by ErikAbele** [comment] 2020-08-29 15:16
Duplicate of #4 – closed.

**Closed as completed** 2020-08-29 15:15 UTC
Labels: duplicate
